name: dart_rss
version: 3.0.3
description: Dart parser for RSS1.0, RSS2.0, Atom feeds.
homepage: https://github.com/Flutter-Bounty-Hunters/dart-rss
repository: https://github.com/Flutter-Bounty-Hunters/dart-rss

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  xml: '>=6.2.0 <7.0.0'
  http: '>=1.1.0 <2.0.0'
  # 0.18.0 is the first version with full Dart 3.0.0 compatibility
  intl: '>=0.18.0 <0.21.0'

dev_dependencies:
  test: ^1.16.4
  lints: ^6.0.0
